# Surge synth build script
# https://aka.ms/yaml

jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-20.04'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        set -o errexit
        python3 -m pip install --upgrade pip
        pip3 install cibuildwheel==2.12.0
        git submodule update --init --recursive
      displayName: Install dependencies
    - bash: cibuildwheel --output-dir wheelhouse src/surge-python
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
